### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by FaTalR** [ndaidong/article-parser#109]
https://www.facebook.com/events/278212406489274
Don't know if facebook doesn't want this type of tools on his site, i will be glad to read your answer !

**Comment by ndaidong** [comment]
@FaTalR I think that a Facebook event is a special type of content, not regular article.

**Comment by FaTalR** [comment]
Thanks for your reply, I have two more questions about your excellent work: is it in your plans to extract the favicon from articles in the future? And I'm really new with this kind of tools so I don't know if I can code it to personalize its behavior, for example to extract a facebook event?

**Comment by ndaidong** [comment]
@FaTalR thank you for your compliment.

I have no plan to extract favicon from article because it's not must-have info, just something to decorate in the view. In additional, it's quite easy to get favicon from a website when you have its URL already, for example  using Google S2: https://www.google.com/s2/favicons?domain=www.facebook.com

Facebook Events are not same as regular article, sometimes they aren't public. The content structure of an event is far different from an article. So you should use a particular tool, such as Facebook Graph API to get it:  https://developers.facebook.com/docs/graph-api/reference/event

**Comment by FaTalR** [comment]
Ah yes thanks, i had forgot S2.
Facebook Graph could have been relevant, but it seems that it does not allow to extract events from users or from pages when we are not a "Facebook marketing partners". Sorry to come back to this, but is it possible or very difficult to add a conditional statement in your code to extract this type of URL?

**Comment by ndaidong** [comment]
@FaTalR basically it's not very difficult, you just need to check the URL, if it belongs to Facebook event, extract it with your own method. However, this lib has been refactored to focus on only purpose: extract general article content. Its current architecture may be not flexible enough.
