### ISSUE TITLE
Request More Data From Extracted Article

### ISSUE THREAD

**Issue by dimaslanjaka** [ndaidong/article-parser#261]
request more data from article result please.
- Modified Date
- Categories
- Tags
![image](https://user-images.githubusercontent.com/12471057/168517811-cd10cf04-c7c6-4f3f-9872-076e31c22b71.png)

**Comment by ndaidong** [comment]
@dimaslanjaka hello, I see that there are very few websites that provide this kind of info, because there is no standard for them yet. 

If you want to classify an article, you can use the simple NLP libraries which support Regression Classifiers such as [natural](https://naturalnode.github.io/natural/bayesian_classifier.html) or Neural Network such as [brainjs](https://github.com/BrainJS/brain.js#for-training-with-neuralnetwork). If I have free time, I can write some tutorials about that.

**Comment by ndaidong** [comment]
@dimaslanjaka yes, `.extract()` method accepts a URL or webpage's HTML source. If you pass a URL, it will automatically retrieve HTML content for you. Otherwise, it starts parsing process immediately. Thus, you can retrieve HTML content manually first, do whatever you want, and call to `extract()`

Here is a simple example, in which we process each step sequentially:

```js
import axios from 'axios'
import { extract } from 'article-parser'

const getHTML = async (url) => {
  const res = await axios.get(url)
  return res.data
}

const yourCustomParser = async (html) => {
  // do something you want with this HTML content
  return {
    categories,
    tags,
    updatedTime
  }
}

const parseArticle = async (url) => {
  const html = await getHTML(url)
  const article = await extract(html)
  const otherData = await yourCustomParser(html)
  // merge them together and return the last result
}
```

Of course, you can do parallel processing to increase performance.

**Comment by dimaslanjaka** [comment]
> @dimaslanjaka yes, `.extract()` method accepts a URL or webpage's HTML source. If you pass a URL, it will automatically retrieve HTML content for you. Otherwise, it starts parsing process immediately. Thus, you can retrieve HTML content manually first, do whatever you want, and call to `extract()`
> 
> Here is a simple example, in which we process each step sequentially:
> 
> ```js
> import axios from 'axios'
> import { extract } from 'article-parser'
> 
> const getHTML = async (url) => {
>   const res = await axios.get(url)
>   return res.data
> }
> 
> const yourCustomParser = async (html) => {
>   // do something you want with this HTML content
>   return {
>     categories,
>     tags,
>     updatedTime
>   }
> }
> 
> const parseArticle = async (url) => {
>   const html = await getHTML(url)
>   const article = await extract(html)
>   const otherData = await yourCustomParser(html)
>   // merge them together and return the last result
> }
> ```
> 
> Of course, you can do parallel processing to increase performance.

done with this snippet
